# Usar a imagem oficial do Node.js
FROM node:22

# Definir o diretório de trabalho
WORKDIR /usr/src/app

# Copiar package.json e package-lock.json primeiro para instalar dependências
COPY ./package*.json .

# Instalar dependências do React
RUN npm install

# Copiar o restante dos arquivos do React
COPY . .

# Construir o projeto React
RUN npm run build

# Expor a porta
EXPOSE 5173

# Comando para rodar o app React
CMD ["npx", "serve", "build"]